kind: pipeline
type: kubernetes
name: nano-node

steps:
  - name: dnsupdate
    image: veriganet/base-image:dind-awscli
    volumes:
      - name: dockersock
        path: /var/run
    settings:
      from_secret: docker_secret_veriga
    environment:
      DOCKER_API_KEY:
        from_secret: docker_api_key
      ECR: veriganet
      REPO_NAME: nano-node
      REPO_TAG: dnsupdate-latest
    commands:
      - sleep 10 # give docker enough time to start
      - docker login -u veriganet -p $DOCKER_API_KEY
      - docker build -t $ECR/$REPO_NAME:$REPO_TAG -f dnsupdate/Dockerfile .
      - docker push $ECR/$REPO_NAME:$REPO_TAG
    when:
      event:
        - push

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}
