apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    # rpc
    {{ if .Values.rpc.beta.enabled }}
    - port: {{ .Values.rpc.beta.port }}
      protocol: TCP
      name: rpc-beta
      targetPort: {{ .Values.rpc.beta.port }}
    {{ end }}
    {{ if .Values.rpc.live.enabled }}
    - port: {{ .Values.rpc.live.port }}
      protocol: TCP
      name: rpc-live
      targetPort: {{ .Values.rpc.live.port }}
    {{ end }}
    {{ if .Values.rpc.test.enabled }}
    - port: {{ .Values.rpc.test.port }}
      protocol: TCP
      name: rpc-test
      targetPort: {{ .Values.rpc.test.port }}
    {{ end }}
    # webSocket
    {{ if .Values.webSocket.beta.enabled }}
    - port: {{ .Values.webSocket.beta.port }}
      protocol: TCP
      name: websocket-beta
      targetPort: {{ .Values.webSocket.beta.port }}
    {{ end }}
    {{ if .Values.webSocket.live.enabled }}
    - port: {{ .Values.webSocket.live.port }}
      protocol: TCP
      name: websocket-live
      targetPort: {{ .Values.webSocket.live.port }}
    {{ end }}
    {{ if .Values.webSocket.test.enabled }}
    - port: {{ .Values.webSocket.test.port }}
      protocol: TCP
      name: websocket-test
      targetPort: {{ .Values.webSocket.test.port }}
    {{ end }}
  selector:
    app: {{ .Values.name }}