apiVersion: skaffold/v2beta21
kind: Config
profiles:
  - name: pre
    deploy:
      kubectl:
        manifests:
          - ./pre.yaml
  - name: test
    deploy:
      helm:
        releases:
          - name: pv
            chartPath: ./helm-charts/pv
            namespace: kor
          - name: node
            chartPath: ./helm-charts/nano-node
            namespace: kor
            setValues:
              abbreviation: kor
              live.peering.enabled: true
              live.peering.port: 7175
              serviceAccount.create: true
          - name: rpc
            chartPath: ./helm-charts/nano-node
            namespace: kor
            setValues:
              abbreviation: kor
              live.rpc.control: false
              #live.rpc.ingress.enabled: false
              #live.rpc.ingress.host: "kor-rpc.verigsvc.com"
              live.rpc.enabled: true
              live.rpc.port: 7076
              live.webSocket.enabled: true
              #live.webSocket.ingress.enabled: false
              #live.webSocket.ingress.host: "kor-ws.verigasvc.com"
              live.webSocket.port: 7078