apiVersion: skaffold/v2beta26
kind: Config
profiles:
  - name: pre
    deploy:
      kubectl:
        manifests:
          - ./pre.yaml
  - name: test
    deploy:
      helm:
        releases:
          - name: pv
            chartPath: ./helm-charts/pv
            namespace: test
          - name: node
            chartPath: ./helm-charts/nano-node
            namespace: test
            setValues:
              abbreviation: test
              live.enabled: "true"
              live.peering.enabled: "true"
              live.peering.port: "7175"
              serviceAccount.create: "true"
              cloudflareZoneName: "verigasvc.com"
          - name: rpc
            chartPath: ./helm-charts/nano-node
            namespace: test
            setValues:
              abbreviation: test
              live.enabled: "true"
              live.rpc.control: "false"
              live.rpc.enabled: "true"
              live.rpc.port: "7076"
              live.webSocket.enabled: "true"
              live.webSocket.port: "7078"
              cloudflareZoneName: "verigasvc.com"
