abbreviation: "kor"

cloudflareAPIToken: "vault:secret/data/cloudflare/#api_key"
cloudflareZoneName: "verigasvc.com"
cloudflareZoneID: "vault:secret/data/cloudflare/#zone_id"

dnsupdate:
  image:
    account: "veriganet"
    tag: "dnsupdate-V22.1"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 50m
      memory: 128Mi

imagePullSecrets:
  - name: registry

preprep:
  image:
    account: "veriganet"
    tag: "preprep-V22.1"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 50m
      memory: 128Mi

live:
  enabled: false
  ipc:
    enabled: false
    ipcPort: 7077
    processIpcPort: ""
  node:
    image:
      account: "veriganet"
      tag: "node-V22.1"
      pullPolicy: Always
    resources:
      requests:
        cpu: 300m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 256Mi
    storage: 10Gi
    replicaCount: 2
  peering:
    enabled: false
    port: 7075
  representative:
    enabled: true
  rpc:
    enabled: false
    control: false
    image:
      account: "veriganet"
      tag: "node-V22.1"
      pullPolicy: Always
    ingress:
      enabled: false
      host: ""
    resources:
      requests:
        cpu: 300m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 256Mi
    storage: 10Gi
    port: 7076
    replicaCount: 2
  webSocket:
    enabled: false
    address: "::1"
    ingress:
      enabled: false
      host: ""
    port: 7078

beta:
  enabled: false
  ips:
    enabled: false
    ipsPort: "56000"
    processIpcPort: ""
  peering:
    enabled: false
    port: "54000"
  rpc:
    enabled: false
    control: false
    ingress:
      enabled: false
      host: ""
    port: "55000"
  webSocket:
    enabled: false
    address: "::1"
    host: "::1"
    port: "57000"

test:
  enabled: false
  ipc:
    enabled: false
    ipsPort: "17077"
    processIpcPort: ""
  peering:
    enabled: false
    port: "44000"
  rpc:
    enabled: false
    control: false
    ingress:
      enabled: false
      host: ""
    port: "45000"
  webSocket:
    enabled: false
    address: "::1"
    host: "::1"
    port: "17078"

serviceAccount:
  create: false
  name: "nano-node"

affinity: {}

nodeSelector: {}

resources: {}

tolerations: []
