apiVersion: v2
description: A Helm chart for creating persistant volume
name: pv
version: 22.1.0
appVersion: 22.1.0
type: application

maintainers:
  - name: verigaNET Infa Team
    email: infra@veriga.net
