storageClassName: nfs-dynamic

live:
  enabled: true
  node:
    enabled: true
    storage: 10Gi
    replicaCount: 2
  peering:
    enabled: true
  rpc:
    enabled: true
    storage: 10Gi
    replicaCount: 2
beta:
  enabled: false
  node:
    storage: 1Gi
  peering:
    enabled: false
    replica: 1
  rpc:
    enabled: false
    storage: 10Gi
    replicaCount: 1
test:
  enabled: false
  node:
    storage: 1Gi
  peering:
    enabled: false
    replicaCount: 1
  rpc:
    enabled: false
    storage: 10Gi
    replicaCount: 1
