# #######
# PEERING
# #######
{{ if eq .Values.live.rpc.enabled true}}
{{ range $i, $e := until (.Values.live.node.replicaCount | int) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-node-live-{{ $i }}
  namespace: {{ $.Release.Namespace }}
spec:
  storageClassName: {{ $.Values.storageClassName }}{{ $i }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $.Values.live.node.storage }}
{{ end }}
{{ end }}

# ###
# RPC
# ###
{{ if eq .Values.live.rpc.enabled true}}
{{ range $i, $e := until (.Values.live.rpc.replicaCount | int) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-rpc-live-{{ $i }}
  namespace: {{ $.Release.Namespace }}
spec:
  storageClassName: {{ $.Values.storageClassName }}{{ $i }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $.Values.live.rpc.storage }}
{{ end }}
{{ end }}
