#
# rpc
#
{{ if eq .Values.live.rpc.ingress.enabled true }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rpc-live
  namespace: {{ .Release.Namespace }}
  labels:
    app: rpc-live
spec:
  rules:
    - host: {{ .Values.live.rpc.ingress.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rpc-live
                port:
                  number: {{ .Values.live.rpc.port }}
{{ end }}
#
# webSocket
#
{{ if eq .Values.live.webSocket.ingress.enabled true }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ws-live
  namespace: {{ .Release.Namespace }}
  labels:
    app: ws-live
spec:
  rules:
    - host: {{ .Values.live.webSocket.ingress.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ws-live
                port:
                  number: {{ .Values.live.webSocket.port }}
{{ end }}