{{ if eq .Values.live.enabled "true" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}-live
  labels:
    app: {{ .Values.name }}-live
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}-live
  serviceName: {{ .Values.name }}-live
  replicas: {{ $.Values.replicaCount }}
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
        vault.security.banzaicloud.io/vault-role: "{{ .Chart.Name }}"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
      labels:
        app: {{ .Values.name }}-live
    spec:
      initContainers:
        - name: dnsupdate
          image: "registry-aws.veriga.net/nano-node:dnsupdate-latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/bin/dnsupdate"]
          env:
            - name: CLOUDFLARE_API_TOKEN
              value: "{{ .Values.cloudflareAPIToken }}"
            - name: CLOUDFLARE_ZONE_NAME
              value: "{{ .Values.cloudflareZoneName }}"
            - name: CLOUDFLARE_ZONE_ID
              value: "{{ .Values.cloudflareZoneID }}"
            - name: ABBREVIATION
              value: "{{ .Values.abbreviation }}"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 200Mi
{{ if eq .Values.live.representative.enabled "true" }}
        - name: preprep
          image: {{ .Values.image.repository }}:preprep-latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/bin/entry_preprep.sh"]
          env:
            - name: ABBREVIATION
              value: {{ .Values.abbreviation }}
            - name: PRIVATE_KEY_REP0
              value: "vault:secret/data/{{ .Values.abbreviation }}/#private_key_rep0"
            - name: PRIVATE_KEY_REP1
              value: "vault:secret/data/{{ .Values.abbreviation }}/#private_key_rep1"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - name: data-{{ .Values.name }}-live
              mountPath: /root/{{ .Values.abbreviation | upper }}
            - name: data-{{ .Values.name }}-live
              mountPath: /root/{{ .Values.abbreviation | title }}
{{ end }}
      containers:
        - name: node-live
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            # peering
            {{ if eq .Values.live.peering.enabled "true" }}
            - containerPort: {{ .Values.live.peering.port }}
              hostPort: {{ .Values.live.peering.port }}
              protocol: TCP
            {{ end }}
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: data-{{ .Values.name }}-live
              mountPath: /root/{{ .Values.abbreviation | upper }}
            - name: data-{{ .Values.name }}-live
              mountPath: /root/{{ .Values.abbreviation | title }}
          livenessProbe:
            # peering
            {{ if eq .Values.live.peering.enabled "true" }}
            tcpSocket:
              port: {{ .Values.live.peering.port }}
            {{ end }}
          readinessProbe:
            # rpc
            {{ if eq .Values.live.peering.enabled "true" }}
            tcpSocket:
              port: {{ .Values.live.peering.port }}
            {{ end }}
      imagePullSecrets:
        - name: registry
      serviceAccountName: "nano-node"
      automountServiceAccountToken: true
  volumeClaimTemplates:
    - metadata:
        name: data-{{ .Values.name }}-live
        namespace: {{ .Release.Namespace }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.storageCapacity }}
{{ end }}