#
# rpc
#
{{ if eq .Values.live.rpc.ingress.enabled true }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rpc-live
  namespace: {{ .Release.Namespace }}
  labels:
    app: rpc-live
  annotations:
    kubernetes.io/ingress.class: {{ .Values.live.ingress.ingressClassName }}
spec:
  ingressClassName: {{ .Values.live.ingressClassName }}
  rules:
    - host: {{ .Values.live.rpc.ingress.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rpc-live
                port:
                  number: {{ .Values.live.rpc.port }}
{{ end }}
#
# webSocket
#
{{ if eq .Values.live.webSocket.ingress.enabled true }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ws-live
  namespace: {{ .Release.Namespace }}
  labels:
    app: ws-live
spec:
  ingressClassName: {{ .Values.live.ingressClassName }}
  rules:
    - host: {{ .Values.live.webSocket.ingress.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ws-live
                port:
                  number: {{ .Values.live.webSocket.port }}
{{ end }}
#
# bootstrap
#
{{ if eq .Values.live.representative.bootstrap.enabled true }}
{{ range $i, $e := until (.Values.live.representative.replicaCount | int) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bootstrap-live-{{ $i }}
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: bootstrap-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
  labels:
    app: bootstrap-live
spec:
  ingressClassName: {{ .Values.live.ingressClassName }}
  rules:
    - host: {{ $.Values.abbreviation }}-rep{{ $i }}.{{ $.Values.domainsvc }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bootstrap-live-{{ $i }}
                port:
                  number: {{ .Values.live.rpc.port }}
{{ end }}
{{ end }}
