#
# rpc
#
{{ if eq .Values.live.rpc.enabled true }}
---
apiVersion: v1
kind: Service
metadata:
  name: rpc-live
  namespace: {{ .Release.Namespace }}
  labels:
    app: rpc-live
spec:
  type: ClusterIP
  ports:
    # rpc
    - port: {{ .Values.live.rpc.port }}
      protocol: TCP
      name: rpc
      targetPort: {{ .Values.live.rpc.port }}
  selector:
    app: rpc-live
{{ end }}
#
# webSocket
#
{{ if eq .Values.live.webSocket.enabled true }}
---
apiVersion: v1
kind: Service
metadata:
  name: ws-live
  labels:
    app: ws-live
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.live.webSocket.port }}
      protocol: TCP
      name: websocket
      targetPort: {{ .Values.live.webSocket.port }}
  selector:
    app: rpc-live
{{ end }}
#
# representative bootstrap
#
{{ if eq .Values.live.representative.bootstrap.enabled true }}
{{ range $i, $e := until (.Values.live.representative.replicaCount | int) }}
---
apiVersion: v1
kind: Service
metadata:
  name: bootstrap-live-{{ $i }}
  labels:
    app: bootstrap-live-{{ $i }}
  namespace: {{ $.Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $.Values.live.rpc.port }}
      protocol: TCP
      name: rpc
      targetPort: {{ $.Values.live.rpc.port }}
  selector:
    statefulset.kubernetes.io/pod-name: node-live-{{ $i }}
{{ end }}
{{ end }}
