#
# rpc
#
{{ if eq .Values.live.rpc.enabled true }}
---
apiVersion: v1
kind: Service
metadata:
  name: rpc-live
  namespace: {{ .Release.Namespace }}
  labels:
    app: rpc-live
spec:
  type: ClusterIP
  ports:
    # rpc
    - port: {{ .Values.live.rpc.port }}
      protocol: TCP
      name: rpc
      targetPort: {{ .Values.live.rpc.port }}
  selector:
    app: rpc-live
{{ end }}
#
# webSocket
#
{{ if eq .Values.live.webSocket.enabled true }}
---
apiVersion: v1
kind: Service
metadata:
  name: ws-live
  labels:
    app: ws-live
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.live.webSocket.port }}
      protocol: TCP
      name: websocket
      targetPort: {{ .Values.live.webSocket.port }}
  selector:
    app: rpc-live
{{ end }}
#
# bootstrap
#
{{ if eq .Values.live.bootstrap.enabled true }}
---
apiVersion: v1
kind: Service
metadata:
  name: bootstrap-live-0
  labels:
    app: bootstrap-live-0
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.live.rpc.port }}
      protocol: TCP
      name: rpc
      targetPort: {{ .Values.live.rpc.port }}
  selector:
    statefulset.kubernetes.io/pod-name: node-live-0
---
apiVersion: v1
kind: Service
metadata:
  name: bootstrap-live-1
  labels:
    app: bootstrap-live-1
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.live.rpc.port }}
      protocol: TCP
      name: rpc
      targetPort: {{ .Values.live.rpc.port }}
  selector:
    statefulset.kubernetes.io/pod-name: node-live-1
---
apiVersion: v1
kind: Service
metadata:
  name: bootstrap-live-2
  labels:
    app: bootstrap-live-2
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.live.rpc.port }}
      protocol: TCP
      name: rpc
      targetPort: {{ .Values.live.rpc.port }}
  selector:
    statefulset.kubernetes.io/pod-name: node-live-2
{{ end }}
